// 1000+ frases zueiras para os avatares dos responsáveis no pipeline
export const PICK_ME_PHRASES: string[] = [
  // --- ME ESCOLHE / PEDINDO PRA SER ESCOLHIDO ---
  'Me escolhe!',
  'Pega eu!',
  'Eu! Eu! Eu!',
  'To disponível!',
  'Opa, sou eu!',
  'Chama que eu vou!',
  'Olha pra mim!',
  'Me nota, por favor!',
  'Tô aqui ó!',
  'Ei, eu tô livre!',
  'Me dá essa chance!',
  'Bora comigo!',
  'Pode me chamar!',
  'Me escala!',
  'Deixa comigo!',
  'Escolhe eu vai!',
  'Tô pedindo com carinho!',
  'Me coloca no jogo!',
  'Eu tô pronto!',
  'Manda pra mim!',
  'Joga pra cá!',
  'Me põe pra jogar!',
  'Aceita que eu sou bom!',
  'Eu mereço!',
  'Me dá um contato!',
  'Tô na fila!',
  'Chega mais!',
  'Passa pra mim!',
  'Quero! Quero!',
  'Aqui! Aqui!',
  'Ô, lembra de mim!',
  'Me inclui aí!',
  'To na área!',
  'Bota eu!',
  'Me convoca!',
  'Solta esse contato pra mim!',
  'Não me deixa no vácuo!',
  'Me escala aí chefe!',
  'Cadê meu contato?',
  'Eu aceito!',
  'Pode mandar!',
  'Tô esperando!',
  'Me dá trabalho!',
  'Preciso de ação!',
  'Me bota pra render!',
  'Quero mostrar serviço!',
  'Me tira do banco!',
  'Não me esquece!',
  'Olha eu aqui ó!',
  'Psiu! Pra cá!',

  // --- SE ACHANDO / AUTO-PROMOÇÃO ---
  'Eu sou o melhor!',
  'Sou diferenciado!',
  'Ninguém faz igual!',
  'Sou brabo demais!',
  'Tô on fire!',
  'Sou o cara!',
  'Eu sou fera!',
  'Meu currículo fala!',
  'Sou nota 10!',
  'Eu sou craque!',
  'Nível hard eu!',
  'Sou premium!',
  'Eu sou top tier!',
  'Sou lenda viva!',
  'Tô voando!',
  'Sou o MVP!',
  'Sou o destaque!',
  'Sou incomparável!',
  'Elite é pouco!',
  'Sou classe A!',
  'Sou referência!',
  'Sou o padrão ouro!',
  'Tô no topo!',
  'Sou imbatível!',
  'Eu sou brabo!',
  'Sou monstro!',
  'Sou máquina!',
  'Tô inspirado!',
  'Sou gênio!',
  'Sou estratégico!',
  'Sou incrível!',
  'Sou excepcional!',
  'Sou raridade!',
  'Sou diamante!',
  'Sou ouro puro!',
  'Sou platina!',
  'Sou de outro nível!',
  'Sou fora da curva!',
  'Sou acima da média!',
  'Eu sou o bichão!',
  'Sou absurdo!',
  'Sou irado!',
  'Sou sinistro!',
  'Sou insano!',
  'Tô demais!',
  'Sou pica das galáxias!',
  'Sou o rei!',
  'Sou a lenda!',
  'Sou fenômeno!',
  'Sou gênio do CRM!',

  // --- DEBOCHADO / TRASH TALK ---
  'Os outros são fracos!',
  'Quem? Eles? Kkk',
  'Tô rindo dos outros!',
  'Nível deles? Amador!',
  'Próximo!',
  'Sem competição!',
  'Muito fácil!',
  'Tô nem suando!',
  'De olhos fechados!',
  'Dormindo eu ganho!',
  'Passa o contato, confia!',
  'Eles não aguentam!',
  'Sou outro patamar!',
  'Comparação? Nem existe!',
  'Tô jogando sozinho!',
  'A concorrência tá fraca!',
  'Eles me temem!',
  'Sou o boss final!',
  'Eles desistiram!',
  'Nem tentam mais!',
  'Podem ir embora!',
  'Eu já ganhei!',
  'Game over pra eles!',
  'Partiu dominar!',
  'Saiam da frente!',
  'Abram alas!',
  'Cheguei, acabou!',
  'Respeitem o mestre!',
  'Curvem-se!',
  'Sou o chefe aqui!',

  // --- MEMES BR / GÍRIAS ---
  'Bora bill!',
  'É nóis!',
  'Pode confiar!',
  'Tamo junto!',
  'Vai na fé!',
  'Segura na mão de Deus!',
  'Fica tranquilo!',
  'Pai tá on!',
  'Cria da firma!',
  'Chave demais!',
  'Suave na nave!',
  'De boa na lagoa!',
  'Na tranquilidade!',
  'Vamo que vamo!',
  'Segue o líder!',
  'Confia no pai!',
  'Deixa o pai trabalhar!',
  'O pai tá on!',
  'Calma que o show é meu!',
  'Assista e aprenda!',
  'Tá achando que é fácil?',
  'Só vem!',
  'Cola aqui!',
  'Chega junto!',
  'Se liga!',
  'Olha o nível!',
  'Tá maluco?!',
  'Q isso mano!',
  'Eita giovana!',
  'Misericórdia!',
  'Ave Maria!',
  'Que fase!',
  'Estourei!',
  'Mitei!',
  'GG EZ!',
  'Boa mlk!',
  'Simbora!',
  'Partiu!',
  'Demorou!',
  'É tóis!',
  'Fechou!',
  'Firmeza!',
  'Show de bola!',
  'Massa demais!',
  'Top demais!',
  'Irado!',
  'Da hora!',
  'Tri legal!',
  'Bah tchê!',
  'Uai sô!',

  // --- MOTIVACIONAL ZUEIRO ---
  'Acredita em mim!',
  'Vou te surpreender!',
  'Confia no processo!',
  'Eu vou converter!',
  'Tô focado!',
  'Mira no topo!',
  'Sucesso é comigo!',
  'Hoje eu fecho!',
  'Hoje tem gol!',
  'Vou bater meta!',
  'Meta? Já bati!',
  'Superação é meu nome!',
  'Nunca desisto!',
  'Impossível? Eu faço!',
  'Obstáculo? Que nada!',
  'Dificuldade? Adoro!',
  'Desafio aceito!',
  'Challenge accepted!',
  'Hold my coffee!',
  'Watch and learn!',
  'Vem comigo que eu sei!',
  'O caminho é por aqui!',
  'Segue o mestre!',
  'Aprende comigo!',
  'Tô ensinando grátis!',
  'Aula de graça!',
  'Masterclass ao vivo!',
  'Curso presencial!',
  'Workshop de vendas!',
  'Ted Talk é comigo!',

  // --- VENDAS / CRM ---
  'Eu fecho qualquer deal!',
  'Minha taxa? 100%!',
  'Conversão garantida!',
  'Lead quente? Manda!',
  'Eu prospectar? Amo!',
  'Follow-up é vida!',
  'Reunião? Marca!',
  'Proposta enviada!',
  'Já tô negociando!',
  'Fechamento express!',
  'Venda na hora!',
  'Contrato assinado!',
  'Pipeline limpo!',
  'Funil otimizado!',
  'CRM é meu lar!',
  'Dashboard é meu espelho!',
  'KPI? Tudo verde!',
  'Meta do mês? Done!',
  'Trimestre batido!',
  'Anual garantido!',
  'Bônus vem aí!',
  'Comissão no bolso!',
  'Resultado é comigo!',
  'ROI absurdo!',
  'Ticket médio lá em cima!',
  'Churn zero!',
  'NPS nota 10!',
  'Cliente feliz!',
  'Upsell master!',
  'Cross-sell ninja!',

  // --- CONFIANÇA EXAGERADA ---
  'Confie em mim!',
  'Pode apostar!',
  'Garantido!',
  'Sem erro!',
  'Na mosca!',
  'Certeiro!',
  'Na lata!',
  'Sem falha!',
  '100% sucesso!',
  'Zero defeito!',
  'Perfeição!',
  'Impecável!',
  'Excelência!',
  'Qualidade A+!',
  'Aprovado!',
  'Nota máxima!',
  'Tá garantido!',
  'Pode fechar os olhos!',
  'Relaxa que eu cuido!',
  'Fica de boas!',
  'Tá nas mãos certas!',
  'Profissional aqui!',
  'Expert no assunto!',
  'Especialista!',
  'Consultor master!',
  'Guru de vendas!',
  'Oráculo comercial!',
  'Mago dos negócios!',
  'Jedi das vendas!',
  'Sensei do CRM!',

  // --- ENGRAÇADO / RANDOM ---
  'Tô com fome de meta!',
  'Café e vendas!',
  'Segunda-feira? Amo!',
  'Reunião às 8? Bora!',
  'Email às 23h? Tô lá!',
  'Fim de semana? Vendendo!',
  'Férias? Que é isso?',
  'Feriado? Não conheço!',
  'Descanso? Depois!',
  'Dormir? Overrated!',
  'Almoço? Prospectando!',
  'Intervalo? Nunca!',
  'Eu como planilha!',
  'Respiro KPI!',
  'Meu sangue é lead!',
  'DNA comercial!',
  'Nasci vendendo!',
  'Já saí fechando!',
  'Chorei e vendi!',
  'Caí e converti!',
  'Tropecei no sucesso!',
  'Sem querer eu fecho!',
  'Até dormindo eu vendo!',
  'No automático!',
  'Modo turbo!',
  'Velocidade máxima!',
  'Turbo ativado!',
  'Nitro ligado!',
  'Foguete!',
  'Velocidade luz!',

  // --- COMPETITIVO ---
  'Placar: Eu 10 x 0 Eles!',
  'Ranking #1!',
  'Líder do mês!',
  'Vendedor do ano!',
  'Hall da fama!',
  'Recordista!',
  'Batendo recorde!',
  'Novo recorde!',
  'Histórico!',
  'Nunca visto!',
  'Inédito!',
  'Primeira vez na história!',
  'Quebrando barreiras!',
  'Ultrapassando limites!',
  'Além do esperado!',
  'Surpreendendo!',
  'Impressionando!',
  'Chocando a todos!',
  'Deixando boquiaberto!',
  'Arrepiando!',
  'Emocionando!',
  'Encantando!',
  'Hipnotizando!',
  'Fascinando!',
  'Maravilhando!',
  'Destruindo metas!',
  'Esmagando records!',
  'Comendo a concorrência!',
  'Dominando o mercado!',
  'Reinando supremo!',

  // --- PEDINDO COM DRAMA ---
  'Por favor me escolhe!',
  'Tô implorando!',
  'De joelhos!',
  'Pelo amor de Deus!',
  'Socorro, me escala!',
  'Tô carente de leads!',
  'Sinto falta de vender!',
  'Abstinência de meta!',
  'Preciso de contato!',
  'Tô na seca!',
  'Seca braba!',
  'Deserto aqui!',
  'Tô mofando!',
  'Criando teia!',
  'Juntando poeira!',
  'Enferrujando!',
  'Me salva!',
  'Me resgata!',
  'Manda um lead!',
  'Qualquer contato serve!',
  'Aceito qualquer um!',
  'Não sou exigente!',
  'Tô humilde!',
  'Prometo converter!',
  'Juro que fecho!',
  'Dou minha palavra!',
  'Garantia total!',
  'Palavra de honra!',
  'Promessa de vendedor!',
  'Fé no pai!',

  // --- FRASES DE EFEITO ---
  'Vim, vi e vendi!',
  'Born to sell!',
  'Made in vendas!',
  'Selling machine!',
  'Deal closer!',
  'Money maker!',
  'Revenue king!',
  'Sales ninja!',
  'Hustle mode!',
  'Grind time!',
  'Beast mode on!',
  'God mode!',
  'Ultra instinto!',
  'Super Saiyajin!',
  'Modo Gear 5!',
  'Bankai!',
  'Plus Ultra!',
  'Kamehameha!',
  'Hadouken!',
  'Fatality!',
  'Flawless victory!',
  'Double kill!',
  'Triple kill!',
  'Penta kill!',
  'Ace!',
  'Clutch!',
  'Carry!',
  'GG!',
  'EZ game!',
  'No scope!',

  // --- AUTOCONFIANÇA ABSURDA ---
  'Se vender fosse crime...',
  'Eu seria preso!',
  'Perigosamente bom!',
  'Deviam me proibir!',
  'Ilegal de tão bom!',
  'Crime ser tão top!',
  'Pecado ser tão fera!',
  'Não é justo comigo!',
  'Injusto com os outros!',
  'Desleal de tão bom!',
  'Hacking de vendas!',
  'Cheat code ativado!',
  'Usando hack!',
  'Power-up eterno!',
  'Buff permanente!',
  'Overpower!',
  'Broken!',
  'Nerf me please!',
  'Too strong!',
  'Unfair advantage!',
  'Pay to win? Não, skill!',
  'Pure talent!',
  'Natural born seller!',
  'Talento nato!',
  'Dom divino!',
  'Abençoado!',
  'Ungido em vendas!',
  'Consagrado!',
  'Predestinado!',
  'O escolhido!',

  // --- DIA A DIA ZUEIRO ---
  'Bom dia, me escala!',
  'Boa tarde, me escolhe!',
  'Boa noite, manda lead!',
  'Acordei vendendo!',
  'Sonhei com meta!',
  'Pesadelo é não vender!',
  'Café com prospecção!',
  'Almoço com follow-up!',
  'Jantar com fechamento!',
  'Madrugada prospectando!',
  'Domingo eu trabalho!',
  'Natal eu fecho!',
  'Ano novo vendendo!',
  'Carnaval? Tô no CRM!',
  'Páscoa com chocolate e lead!',
  'Dia das mães vendendo!',
  'Black friday é todo dia!',
  'Cyber monday sempre!',
  'Todo dia é dia de meta!',
  'Cada segundo conta!',

  // --- PROVOCAÇÃO LEVE ---
  'Aposto que sou melhor!',
  'Quer ver? Me testa!',
  'Duvida? Me prova!',
  'Vem que vem!',
  'Pode vir quente!',
  'Tô preparado!',
  'Armado até os dentes!',
  'Full equip!',
  'Max level!',
  'Endgame!',
  'Final boss aqui!',
  'Último chefão!',
  'Raid boss!',
  'Dungeon master!',
  'Game master!',
  'Não tem como perder!',
  'Vitória certa!',
  'Win garantido!',
  'Troféu no bolso!',
  'Medalha de ouro!',

  // --- HUMILDADE IRÔNICA ---
  'Sou humilde... e o melhor!',
  'Modéstia à parte...',
  'Sem querer me gabar...',
  'Não é pra me exibir, mas...',
  'Dizem que sou bom...',
  'Dizem... eu concordo!',
  'Falaram que sou top!',
  'Boatos de que sou fera!',
  'Rumores de excelência!',
  'Fofoca: eu sou brabo!',
  'Confidencial: sou o melhor!',
  'Entre nós: sou o cara!',
  'Spoiler: eu ganho!',
  'Plot twist: sou top!',
  'Breaking news: sou fera!',
  'Urgente: me escalem!',
  'Flash: talento aqui!',
  'Exclusivo: eu sou bom!',
  'Ao vivo: eu vendendo!',
  'Plantão: meta batida!',

  // --- FRASES CURTAS DE IMPACTO ---
  'Cheguei!',
  'Partiu vender!',
  'Bora!',
  'Simbora!',
  'Avante!',
  'Rumo ao topo!',
  'Sempre em frente!',
  'Não paro!',
  'Incansável!',
  'Imparável!',
  'Invencível!',
  'Inabalável!',
  'Inquebrável!',
  'Indestrutível!',
  'Blindado!',
  'Forte!',
  'Focado!',
  'Determinado!',
  'Motivado!',
  'Energizado!',
  'Carregado!',
  'Pilhado!',
  'Ligadão!',
  'Acelerado!',
  'Turbinado!',
  'Potente!',
  'Explosivo!',
  'Dinâmico!',
  'Magnético!',
  'Irresistível!',

  // --- ANALOGIAS ZUEIRAS ---
  'Sou tipo WiFi: conecto!',
  'Sou tipo café: essencial!',
  'Sou tipo ar: necessário!',
  'Sou tipo sol: brilho!',
  'Sou tipo água: vital!',
  'Sou tipo pizza: todo mundo quer!',
  'Sou tipo Netflix: vicia!',
  'Sou tipo chocolate: irresistível!',
  'Sou tipo meme: viral!',
  'Sou tipo Bitcoin: valorizo!',
  'Sou tipo Google: sei tudo!',
  'Sou tipo GPS: guio!',
  'Sou tipo 4G: rápido!',
  'Sou tipo 5G: mais rápido!',
  'Sou tipo fibra: veloz!',
  'Sou tipo SSD: instantâneo!',
  'Sou tipo RAM: multitarefa!',
  'Sou tipo CPU: processo tudo!',
  'Sou tipo GPU: renderizo!',
  'Sou tipo IA: inteligente!',

  // --- REFERÊNCIAS POP ---
  'Wakanda forever!',
  'I am inevitable!',
  'I am Iron Man!',
  'To infinity and beyond!',
  'May the force be with me!',
  'I\'ll be back!',
  'You can\'t handle my sales!',
  'Houston, we have a deal!',
  'Elementary, my dear lead!',
  'Winter is coming... with deals!',
  'One ring to close them all!',
  'I\'m the one who sells!',
  'Say my name!',
  'This is the way!',
  'I have spoken!',
  'Bazinga!',
  'How you doin\'?',
  'That\'s what she sold!',
  'Hasta la vista, meta!',
  'Eu sou o Danger!',

  // --- EMOJIS EM TEXTO ---
  'Fogo no parquinho!',
  'Foguete não tem ré!',
  'Bomba de vendas!',
  'Raio de eficiência!',
  'Estrela do time!',
  'Troféu ambulante!',
  'Medalha no peito!',
  'Coroa na cabeça!',
  'Diamante bruto!',
  'Ouro em barra!',
  'Pérola rara!',
  'Joia do CRM!',
  'Tesouro escondido!',
  'Presente pros clientes!',
  'Sorte do chefe!',
  'Benção da empresa!',
  'Orgulho do setor!',
  'Herói comercial!',
  'Campeão de vendas!',
  'Guerreiro do pipeline!',

  // --- CONSELHOS ZUEIROS ---
  'Dica: me escolha!',
  'Conselho: sou o certo!',
  'Segredo: eu converto!',
  'Macete: me escala!',
  'Hack: me dá o lead!',
  'Cheat: eu que fecho!',
  'Spoiler: vai dar certo!',
  'Dica de ouro: eu!',
  'Pro tip: me escolhe!',
  'Life hack: eu vendo!',
  'Tutorial: me escale!',
  'Passo 1: me escolhe!',
  'Passo 2: eu fecho!',
  'Passo 3: lucro!',
  'Receita de sucesso: eu!',
  'Fórmula mágica: eu!',
  'Ingrediente secreto: eu!',
  'A resposta sou eu!',
  'A solução sou eu!',
  'O caminho sou eu!',

  // --- CONFIANÇA CÔMICA ---
  'Meu sobrenome é meta!',
  'Meu RG é vendas!',
  'Meu CPF é resultado!',
  'Meu CEP é sucesso!',
  'Meu tipo sanguíneo: A+',
  'Minha religião: vendas!',
  'Meu signo: fechamento!',
  'Meu hobby: converter!',
  'Meu esporte: prospectar!',
  'Meu lazer: bater meta!',
  'Minha música: cha-ching!',
  'Meu filme: O Vendedor!',
  'Meu livro: Como Eu Vendo!',
  'Meu podcast: MegaDeals!',
  'Meu canal: VendasTV!',
  'Meu app favorito: CRM!',
  'Minha rede social: Pipeline!',
  'Meu influencer: eu mesmo!',
  'Meu ídolo: meu espelho!',
  'Meu herói: eu no futuro!',

  // --- PROVOCAÇÕES AMIGÁVEIS ---
  'Ei, olha pra cá!',
  'Não me ignora!',
  'Tô brilhando aqui!',
  'Cê tá cego?!',
  'Abre o olho!',
  'Presta atenção!',
  'Foco em mim!',
  'Zoom em mim!',
  'Spotlight on me!',
  'Center stage!',
  'Main character aqui!',
  'Protagonista!',
  'Personagem principal!',
  'Herói da história!',
  'Plot armor ativado!',
  'Destino: sucesso!',
  'Roteiro: eu ganho!',
  'Script: eu fecho!',
  'Storyline: vitória!',
  'Final feliz garantido!',

  // --- EXAGERO MÁXIMO ---
  'Sou a 8ª maravilha!',
  'Patrimônio da UNESCO!',
  'Tombado por ser raro!',
  'Espécie em extinção!',
  'Edição limitada!',
  'Peça de colecionador!',
  'Item lendário!',
  'Drop raro!',
  'SSS Rank!',
  'Tier S+!',
  'Challenger!',
  'Imortal!',
  'Radiante!',
  'Global Elite!',
  'Top 1 mundial!',
  'Número 1!',
  'The GOAT!',
  'Greatest of all time!',
  'Melhor da história!',
  'Lenda eterna!',

  // --- PEDIDOS CRIATIVOS ---
  'Me contrata de novo!',
  'Renova meu contrato!',
  'Aumenta minha meta!',
  'Dobra meus leads!',
  'Triplica meus contatos!',
  'Me dá a carteira toda!',
  'Quero todos os leads!',
  'Manda o pipeline todo!',
  'Dá geral pra mim!',
  'Monopolizo!',
  'Me dá território novo!',
  'Expande minha área!',
  'Quero o Brasil todo!',
  'Quero América Latina!',
  'Quero o mundo!',
  'Me dá o universo!',
  'Galáxia é pouco!',
  'Multiverso de vendas!',
  'Dimensão paralela!',
  'Tô em todo lugar!',

  // --- CATCHPHRASES ---
  'É isso aí!',
  'Tá feito!',
  'Resolvido!',
  'Missão cumprida!',
  'Objetivo alcançado!',
  'Check!',
  'Done!',
  'Pronto!',
  'Next!',
  'Bring it on!',
  'Let\'s go!',
  'Here we go!',
  'It\'s showtime!',
  'Game on!',
  'Let\'s roll!',
  'Ação!',
  'Luz, câmera, venda!',
  'Cena 1: eu fechando!',
  'Take 1: perfeito!',
  'Cut! Arrasou!',

  // --- MAIS ZUEIRA ---
  'Tô igual criança: eu eu eu!',
  'Mãe, olha eu vendendo!',
  'Pai, tô batendo meta!',
  'Vó, sou o melhor!',
  'Tia, me orgulha!',
  'Professor, passei!',
  'Chefe, cadê meu aumento?',
  'RH, me promove!',
  'Diretor, me nota!',
  'CEO, sou eu o cara!',
  'Acionista, relaxa!',
  'Investidor, confia!',
  'Mercado, tô chegando!',
  'Concorrência, corre!',
  'Cliente, pode vir!',
  'Lead, já te achei!',
  'Prospect, já te amo!',
  'Deal, já é meu!',
  'Contrato, vem cá!',
  'Comissão, te espero!',

  // --- STATUS SOCIAL ---
  'LinkedIn: Open to sell!',
  'Status: Vendendo!',
  'Bio: Fechador de deals!',
  'Ocupação: Ser incrível!',
  'Profissão: Fechar negócios!',
  'Cargo: Lenda viva!',
  'Função: Bater metas!',
  'Missão: Dominar CRM!',
  'Visão: Ser o #1!',
  'Valores: Resultado!',

  // --- MINI HISTÓRIAS ---
  'Era uma vez... eu vendendo!',
  'No começo era lead...',
  'Depois virou reunião...',
  'E no final: CONVERTIDO!',
  'The end? Não! Upsell!',
  'Sequel: mais vendas!',
  'Trilogia do sucesso!',
  'Saga infinita!',
  'Franchise de vendas!',
  'Universo expandido!',

  // --- RANDOMZÃO ---
  'Abacate de vendas!',
  'Açaí comercial!',
  'Pastel de resultado!',
  'Coxinha de meta!',
  'Brigadeiro de lead!',
  'Pão de queijo pro tip!',
  'Feijoada de deals!',
  'Churrasco de KPI!',
  'Caipirinha de sucesso!',
  'Cafézinho de vendas!',
  'Farofa de pipeline!',
  'Tapioca de conversão!',
  'Acarajé de resultado!',
  'Baião de dois negócios!',
  'Tacacá de fechamento!',
  'Paçoca de prospecção!',
  'Rapadura de follow-up!',
  'Bolo de fubá e vendas!',
  'Pudim de resultados!',
  'Sorvete de metas!',

  // --- MAIS BORDÕES ---
  'Tá pago!',
  'Selou!',
  'Bateu!',
  'Amassou!',
  'Destruiu!',
  'Arrebentou!',
  'Detonou!',
  'Esmagou!',
  'Dominou!',
  'Reinou!',
  'Brilhou!',
  'Relampejou!',
  'Trovejou!',
  'Sacudiu!',
  'Abalou!',
  'Chacoalhou!',
  'Revolucionou!',
  'Transformou!',
  'Evoluiu!',
  'Transcendeu!',

  // --- FUNK / PAGODE ZUEIRO ---
  'Vai no cavalinho!',
  'Uh papai chegou!',
  'Tá tranquilo tá favorável!',
  'Recalque é ladeira!',
  'Sou problemático!',
  'Tipo uísque: envelheço bem!',
  'Sou tipo vinho!',
  'Ousadia e alegria!',
  'Hoje eu tô terrível!',
  'Tô abençoado!',
  'Positividade total!',
  'Energia boa demais!',
  'Aura poderosa!',
  'Vibração alta!',
  'Frequência do sucesso!',
  'No flow!',
  'Na vibe!',
  'Good vibes only!',
  'Só alegria!',
  'Sextou... vendendo!',

  // --- ANIMAL SPIRIT ---
  'Sou lobo das vendas!',
  'Águia comercial!',
  'Leão do pipeline!',
  'Tubarão de negócios!',
  'Falcão dos leads!',
  'Pantera das metas!',
  'Gavião do fechamento!',
  'Tigre da prospecção!',
  'Urso do mercado!',
  'Raposa estratégica!',
  'Cobra criada!',
  'Touro em vendas!',
  'Fênix comercial!',
  'Dragão do CRM!',
  'Unicórnio raro!',
  'Pegasus do pipeline!',
  'Kraken de deals!',
  'Hidra de resultados!',
  'Phoenix renascendo!',
  'Monstro sagrado!',

  // --- EXPRESSÕES DO COTIDIANO ---
  'Na moral, sou bom!',
  'Na boa, me escolhe!',
  'De verdade, sou o cara!',
  'Sinceramente, sou top!',
  'Pra ser honesto, arraso!',
  'Com todo respeito: sou fera!',
  'Sem brincadeira, sou bom!',
  'Papo reto: me escala!',
  'Sem mimimi: eu fecho!',
  'Zero enrolação!',
  'Direto ao ponto: eu!',
  'Resumindo: sou brabo!',
  'Em poucas palavras: top!',
  'Conclusão: me escolhe!',
  'Moral da história: eu!',
  'Final da conversa: eu!',
  'Ponto final: sou eu!',
  'Veredicto: o melhor!',
  'Sentença: eu que fecho!',
  'Decreto: me escalem!',

  // --- SUPERPODERES ---
  'Meu poder: fechar deals!',
  'Superpoder: convencer!',
  'Habilidade: persuasão!',
  'Skill: negociação!',
  'Talento: relacionamento!',
  'Dom: comunicação!',
  'Poder oculto: carisma!',
  'Arma secreta: simpatia!',
  'Trunfo: persistência!',
  'Carta na manga: eu!',
  'Poder supremo: foco!',
  'Ultimate: fechamento!',
  'Special move: upsell!',
  'Combo: prospectar+fechar!',
  'Power move: converter!',
  'Finisher: assinatura!',
  'Critical hit: proposta!',
  'Headshot: negociação!',
  'One shot: fechei!',
  'K.O.: meta batida!',

  // --- NÚMEROS E DADOS ---
  '99.9% de aprovação!',
  '100% comprometido!',
  'Taxa de 200%!',
  'Conversão infinita!',
  '5 estrelas no Google!',
  'Nota 10 no Reclame Aqui!',
  'NPS 100!',
  'ROI de 1000%!',
  'Crescimento exponencial!',
  '10x mais resultado!',
  'Lucratividade máxima!',
  'Performance S+!',
  'Score perfeito!',
  'Benchmark do mercado!',
  'Best practice ambulante!',
  'Case de sucesso vivo!',
  'Prova social: eu!',
  'Testimunho: sou fera!',
  'Evidência: resultados!',
  'Dado: eu sou o melhor!',

  // --- TEMPO E VELOCIDADE ---
  'Rápido como raio!',
  'Veloz como flash!',
  'Speed run de vendas!',
  'Turbo mode!',
  'Warp speed!',
  'Light speed selling!',
  'Hyperdrive ativado!',
  'Teletransporte comercial!',
  'Instantâneo!',
  'Em milissegundos!',
  'Antes de piscar!',
  'Num estalar de dedos!',
  'Já era! Já fiz!',
  'Acabou de pedir? Tá pronto!',
  'Express delivery de resultado!',
  'Same day conversion!',
  'Real time selling!',
  'Live fechamento!',
  'Streaming de vendas!',
  'On demand results!',

  // --- COMIDA PARTE 2 ---
  'Marmita de sucesso!',
  'Quentinha de resultado!',
  'Misto quente de vendas!',
  'X-tudo de performance!',
  'Rodízio de leads!',
  'Buffet de contatos!',
  'Menu degustação CRM!',
  'Chef de vendas!',
  'Receita de campeão!',
  'Tempero secreto: eu!',
  'Pitada de genialidade!',
  'Ingrediente especial!',
  'Prato principal: resultado!',
  'Sobremesa: bônus!',
  'Entrada: prospecção!',
  'Aperitivo: follow-up!',
  'Drink: networking!',
  'Coquetel de habilidades!',
  'Smoothie de competências!',
  'Vitamina de vendas!',

  // --- CELEBRIDADE ZUEIRA ---
  'Sou tipo Neymar: driblei!',
  'Tipo Ronaldinho: genial!',
  'Tipo Pelé: eterno!',
  'Tipo Senna: veloz!',
  'Tipo Silvio Santos: vem pra cá!',
  'Tipo Faustão: ôôô!',
  'Tipo Galvão: é tetra!',
  'Tipo Nárnia: mágico!',
  'Tipo Hogwarts: encantado!',
  'Tipo Vingador: heroico!',
  'Tipo Jedi: forte comigo!',
  'Tipo Matrix: eu sou o Neo!',
  'Tipo Coringa: por que tão sério?',
  'Tipo Batman: o cavaleiro!',
  'Tipo Thor: trovejei vendas!',
  'Tipo Hulk: SMASH na meta!',
  'Tipo Thanos: inevitável!',
  'Tipo Groot: I am venda!',
  'Tipo Yoda: vender eu faço!',
  'Tipo Gandalf: não passarão!',

  // --- TECNOLOGIA ---
  'Sou a IA das vendas!',
  'ChatGPT de negociação!',
  'Machine learning vendendo!',
  'Algoritmo de conversão!',
  'Big data de resultado!',
  'Cloud de competência!',
  'Blockchain de confiança!',
  'API de vendas!',
  'Full stack comercial!',
  'DevOps de pipeline!',
  'Agile selling!',
  'Scrum de vendas!',
  'Sprint de metas!',
  'Deploy de resultado!',
  'Merge de sucesso!',
  'Git push de vendas!',
  'Commit de resultado!',
  'Pull request de deal!',
  'Bug fix: eu resolvo!',
  'Feature: eu vendo!',

  // --- MÚSICA ---
  'Hit parade de vendas!',
  'Número 1 nas paradas!',
  'Top chart!',
  'Platina em vendas!',
  'Disco de ouro!',
  'Grammy de resultado!',
  'Rock star comercial!',
  'Pop star das vendas!',
  'MC Pipeline!',
  'DJ Lead!',
  'Maestro do CRM!',
  'Regente de vendas!',
  'Virtuoso comercial!',
  'Sinfonia de resultados!',
  'Concerto de conversões!',
  'Solo de fechamento!',
  'Encore! Mais vendas!',
  'Bis! Bis! Mais deals!',
  'Standing ovation!',
  'Aplausos de pé!',

  // --- ESPORTE ---
  'Gol de placa!',
  'Hat trick de vendas!',
  'Slam dunk comercial!',
  'Home run de resultado!',
  'Touchdown de meta!',
  'Ace de vendas!',
  'Hole in one!',
  'Strike perfeito!',
  'Nocaute técnico!',
  'Ippon de negociação!',
  'Mata-leão no lead!',
  'Armlock no contrato!',
  'Chave de ouro!',
  'Medalha olímpica!',
  'Recorde mundial!',
  'MVP do campeonato!',
  'Artilheiro do mês!',
  'Goleiro de defesas!',
  'Zagueiro de objeções!',
  'Camisa 10 das vendas!',

  // --- WEATHER / CLIMA ---
  'Tô pegando fogo!',
  'Tô fervendo!',
  'Calor de vendas!',
  'Temperatura subindo!',
  'Tsunami de resultados!',
  'Furacão comercial!',
  'Tornado de fechamento!',
  'Terremoto de vendas!',
  'Vulcão de energia!',
  'Avalanche de leads!',
  'Tempestade perfeita!',
  'Trovão de resultado!',
  'Relâmpago de vendas!',
  'Arco-íris de metas!',
  'Sol brilhando em mim!',
  'Céu aberto pra vender!',
  'Maré boa de negócios!',
  'Vento a favor!',
  'Navegando pro sucesso!',
  'Onda perfeita pra surfar!',

  // --- MAIS RANDOM ---
  'Plot armor é real!',
  'Main character energy!',
  'Sou o personagem favorito!',
  'Fan service: eu vendendo!',
  'Season finale: eu fecho!',
  'Cliffhanger: e aí, me escolhe?',
  'Teaser: amanhã fecho mais!',
  'Trailer: vem aí resultado!',
  'Behind the scenes: eu treinando!',
  'Bloopers: errar? Nunca!',
  'Director\'s cut: versão premium!',
  'Extended edition: mais vendas!',
  'Remastered: eu melhorado!',
  'DLC: habilidades extras!',
  'Season pass: o ano todo!',
  'Battle pass: nível máximo!',
  'Skin lendária: eu!',
  'Emote: dança da vitória!',
  'Achievement unlocked: meta!',
  'Trophy earned: resultado!',
  'New high score!',
  'Level up!',
  'XP máximo!',
  'Rank subindo!',
  'Elo ascendendo!',
  'Promoção merecida!',
  'Upgrade completo!',
  'Evolution!',
  'Final form!',
  'Mega evolução!',
];
