// Frases tristes/dramáticas para quem NÃO está em 1o no ranking
export const SAD_PHRASES: string[] = [
  'Snif snif...',
  'Que tristeza...',
  'Não é justo!',
  'Buááá!',
  'Tô triste...',
  'Chateado!',
  'Injustiça!',
  'Por que eu?',
  'Cadê meus leads?',
  'Ninguém me ama...',
  'Esqueceram de mim!',
  'Tô no banco...',
  'Reserva eterna...',
  'Segunda divisão...',
  'Rebaixado!',
  'Zona do rebaixamento!',
  'Lanterna...',
  'Último lugar...',
  'Tô na fila...',
  'Esperando minha vez...',
  'Um dia eu chego lá...',
  'Sonho distante...',
  'Meta inalcançável...',
  'Tô ficando pra trás!',
  'Ele tá voando e eu...',
  'Perdendo feio!',
  'Tomando de goleada!',
  'Apanhando!',
  'Derrota amarga!',
  'Gosto de derrota...',
  'Sabor de vice...',
  'Quase lá... quase!',
  'Sempre quase!',
  'Nunca eu...',
  'Vou chorar no banho!',
  'Tô mal!',
  'Deprimido!',
  'Devastado!',
  'Arrasado!',
  'Destruído!',
  'Socorro!',
  'Me ajuda!',
  'Preciso de leads!',
  'Cadê meus contatos?',
  'Tô na seca total!',
  'Deserto aqui...',
  'Tá osso!',
  'Tá difícil!',
  'Complicou!',
  'Ferrou!',
  'Lascou!',
  'Deus me livre!',
  'Misericórdia!',
  'Pai amado!',
  'Vixe maria!',
  'Eita nóis!',
  'Cruz credo!',
  'Não tô acreditando!',
  'Possível não!',
  'Inacreditável!',
  'Como assim?!',
  'Não pode ser!',
  'É mentira!',
  'Recuso aceitar!',
  'Negação total!',
  'Em choque!',
  'Paralisado!',
  'Sem reação!',
  'Sem palavras...',
  'Emudeci...',
  'Calado de tristeza!',
  'Silêncio de derrota...',
  'Chorando em silêncio...',
  'Lágrimas caindo...',
  'Coração partido!',
  'Alma ferida!',
  'Ego destruído!',
  'Orgulho quebrado!',
  'Autoestima lá embaixo!',
  'No fundo do poço!',
  'Rock bottom!',
  'Game over pra mim...',
  'Eliminado!',
  'Desclassificado!',
  'Fora do jogo!',
  'Banco de reservas!',
  'Esquentando banco...',
  'Torcida de sofá...',
  'Assistindo o show...',
  'Plateia...',
  'Figurante...',
  'Personagem secundário!',
  'NPC das vendas!',
  'Background character!',
  'Extra do filme...',
  'Nem créditos eu tenho!',
  'Cena deletada!',
  'Cortaram minha parte!',
  'Edit: removido!',
  'Mês que vem eu volto!',
  'Amanhã é outro dia...',
  'Semana que vem melhora...',
  'Ano que vem é meu!',
  'Próxima vida talvez...',
  'Se eu renascer...',
  'Reencarnação de vendas!',
  'Queria ser ele...',
  'Inveja branca...',
  'Admiração... e dor!',
  'Parabéns... eu acho!',
  'Ele merece... acho!',
  'Tá bom então...',
  'Aceitando a derrota...',
  'Engolindo o choro!',
  'Segurando a lágrima!',
  'Olho marejado!',
  'Lábio tremendo!',
  'Queixo caindo!',
  'Ombros caídos!',
  'Cabeça baixa...',
  'Arrastando os pés...',
  'Sem ânimo!',
  'Sem energia!',
  'Bateria em 1%!',
  'Desligando...',
  'Modo economia!',
  'Hibernando...',
  'Standby eterno!',
  'Offline de tristeza!',
  'Desconectado!',
  'Wi-Fi da felicidade caiu!',
  'Sinal perdido!',
  'Fora de área!',
  'Sem cobertura!',
  'Error 404: vitória!',
  'Bug: não converto!',
  'Crash de vendas!',
  'Blue screen of sad!',
  'Kernel panic!',
  'Fatal error!',
  'Unhandled rejection!',
  'Promise rejected!',
  'Timeout de resultado!',
  'Connection lost!',
  'Até o café tá amargo!',
  'Comida sem sal...',
  'Vida sem graça...',
  'Dia nublado...',
  'Chuva na alma!',
  'Tempestade interior!',
  'Dilúvio de tristeza!',
  'Maré baixa...',
  'Vento frio...',
  'Inverno eterno!',
  'Noite sem fim...',
  'Escuridão total!',
  'Sem luz no túnel!',
  'Túnel infinito!',
  'Buraco negro!',
  'Vácuo existencial!',
  'Crise de identidade!',
  'Quem sou eu?',
  'Pra que vendas?',
  'Sentido da vida?',
  'Questionando tudo!',
  'Existencialismo puro!',
  'Niilismo comercial!',
  'Filosofando na derrota!',
  'Pensativo e triste...',
  'Reflexivo e cabisbaixo...',
  'Contemplando o fracasso...',
  'Meditando na perda...',
  'Rezando por leads!',
  'Fazendo simpatia!',
  'Acendendo vela!',
  'Jogando búzios!',
  'Pedindo pro universo!',
  'Manifestando vendas!',
  'Lei da atração cadê?',
  'Karma tá pesado!',
  'Que fase...',
  'Momento difícil...',
  'Período turbulento...',
  'Travessia no deserto!',
  'Quarentena de vendas!',
  'Lockdown de leads!',
  'Isolamento comercial!',
  'Distanciamento do sucesso!',
  'Máscara de tristeza!',
  'Vacina de motivação cadê?',
  'Dose de ânimo por favor!',
  'Tô precisando de ajuda!',
  'SOS vendas!',
  'Mayday mayday!',
  'Pan pan pan!',
  'Código vermelho!',
  'Alerta máximo!',
  'Situação crítica!',
  'Estado de emergência!',
  'Plano B? Não tenho!',
  'Plano C? Chorar!',
  'Plano D: Desespero!',
  'Plano E: Esperança...',
  'Plano F: Fé!',
  'Último recurso!',
  'Cartada final!',
  'Chance derradeira!',
  'Oportunidade última!',
  'Suspiro final...',
  'Ele é bom... admito!',
  'Reconheço a derrota...',
  'Merecido... pra ele!',
  'Boa pra ele!',
  'Parabéns... vou chorar!',
  'Festa... dos outros!',
  'Champagne... pra ele!',
  'Troféu... não é meu!',
  'Pódio? Longe!',
  'Medalha de consolação!',
  'Certificado de presença!',
  'Participei... e perdi!',
  'Ao menos tentei...',
  'Dei meu melhor... foi pouco!',
  'Não foi suficiente...',
  'Preciso melhorar...',
  'Voltando pra treinar!',
  'Recomeçando do zero!',
  'Reset total!',
  'Novo começo amanhã!',
  'Tô na lona mas me levanto!',
  'Caí... tô tentando levantar!',
  'De joelhos... quase em pé!',
  'Cambaleando...',
  'Zonzo de perder!',
  'Tonto da derrota!',
  'Grogue de tanto apanhar!',
  'Contagem regressiva pra cair!',
  '3... 2... 1... nocauteado!',
  'Lona! Lona! Lona!',
  'O juiz contou até 10...',
  'Toalha jogada!',
  'Desisti... por hoje!',
  'Amanhã é guerra!',
  'Revanche vem aí!',
  'Volta por cima!',
  'Não acabou ainda!',
  'Eu volto mais forte!',
  'Preparem-se!',
  'É só o começo!',
  'A vingança vem!',
  'Próximo round é meu!',
  'Aguardem!',
];
